[theme]
primaryColor = "#4682B4"    # Azul Aço (mais escuro para os botões)
backgroundColor = "#2F4F4F" # Azul Escuro (fundo escuro)
secondaryBackgroundColor = "#1C2833" # Fundo de widgets mais escuro
textColor = "#FFFFFF"       # Texto branco para contraste

